[2020-03-12 16:41:23,873] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: register Line: 33} [IP: 127.0.0.1] [Message: El usuario pepe se ha registrado]
[2020-03-12 16:41:23,984] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: register Line: 36} [User: pepe] [Message: Ha añadido correctamente un dispositivo de confianza]
[2020-03-12 16:41:26,636] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: register Line: 38} [User: pepe] [Message: Ha recibido el correo de confirmacion]
[2020-03-12 16:42:09,264] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: login Line: 72} [IP: 127.0.0.1] Intento de inicio de sesion sin cuenta validad por el usuario pepe]
[2020-03-12 16:42:51,021] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: login Line: 64} [IP: 127.0.0.1] [Message: El usuario pepe se ha logeado]
[2020-03-12 16:43:11,416] WARNING - {Dir /home/pepe/Desktop/mediumPepe/medium/posts/routes.py: Function: update_post Line: 46} [User: pepe] [Message: Ha intenatado modificar el post 2 que no es suyo]
[2020-03-12 16:43:44,233] WARNING - {Dir /home/pepe/Desktop/mediumPepe/medium/posts/routes.py: Function: new_post Line: 24} [User: pepe] [Message: Ha creado un nuevo post]
[2020-03-12 16:45:08,308] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: login Line: 68} [IP: 127.0.0.1] Intento de inicio de sesion desde un nuevo dispisitivo, pasamos a token de verifiacion con el usurio pepe]
[2020-03-12 16:46:06,382] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: token Line: 99} [IP: 127.0.0.1] [Message: El usuario pepe se ha logeado]
[2020-03-12 16:46:11,102] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: logout Line: 113} [User: pepe] [Message: Ha cerrado sesion]
[2020-03-12 16:46:18,334] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: login Line: 68} [IP: 127.0.0.1] Intento de inicio de sesion desde un nuevo dispisitivo, pasamos a token de verifiacion con el usurio pepe]
[2020-03-12 16:46:23,632] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: token Line: 94} [User: pepe] [Message: Ha añadido correctamente un nuevo dispositivo de confianza]
[2020-03-12 16:46:23,635] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: token Line: 99} [IP: 127.0.0.1] [Message: El usuario pepe se ha logeado]
[2020-03-12 16:46:27,452] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: logout Line: 113} [User: pepe] [Message: Ha cerrado sesion]
[2020-03-12 16:46:34,356] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: login Line: 64} [IP: 127.0.0.1] [Message: El usuario pepe se ha logeado]
[2020-03-12 16:46:43,747] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: logout Line: 113} [User: pepe] [Message: Ha cerrado sesion]
[2020-03-12 16:48:49,291] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/posts/routes.py: Function: share_post Line: 102} [User: pepe] [Message: Ha creado enlace para compartir el post 5]
[2020-03-12 16:49:58,771] WARNING - {Dir /home/pepe/Desktop/mediumPepe/medium/posts/routes.py: Function: update_post Line: 54} [User: pepe] [Message: Ha modficado el post 5]
[2020-03-12 16:50:13,460] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/posts/routes.py: Function: disallow_post Line: 117} [User: pepe] [Message: Ha eliminado el enlace para compartir el post 5]
[2020-03-12 16:50:16,626] WARNING - {Dir /home/pepe/Desktop/mediumPepe/medium/posts/routes.py: Function: token_share_post Line: 134} [Ip: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0] [Message: Ha intentado ver un post mediante un token invalido]
[2020-03-12 16:50:38,810] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: logout Line: 113} [User: pepe] [Message: Ha cerrado sesion]
[2020-03-12 16:51:12,902] INFO - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: reset_request Line: 231} [IP: 127.0.0.1] [Message: EL usuario va a proceder a las preguntas para reseteo de contraseña pepe]
[2020-03-12 16:54:21,393] WARNING - {Dir /home/pepe/Desktop/mediumPepe/medium/users/routes.py: Function: challenge Line: 268} [User: pepe] [Message: No ha completado las preguntas personales ni el token de seguridad]
